[package]
name = "snake"
version = "0.1.0"
authors = ["illemonati <tonymiaotong@tioft.tech>"]

[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"
